#!/bin/bash
# Source common settings
source /usr/share/ganeti/extstorage/v7000/settings.sh
# Create volume
CREATE=`$SSH svctask mkvdisk -cache readwrite -copies 1 -iogrp io_grp0 -mdiskgrp $POOL -name ganeti_${VOL_NAME} -size $VOL_SIZE -unit mb -vtype striped`
echo $DATE "Create: " $CREATE >>$LOG
