#!/bin/bash
# Source common settings
source /usr/share/ganeti/extstorage/v7000/settings.sh
# Get diskname
DISKNAME=`$SSH lsvdisk ganeti_${VOL_NAME}|grep vdisk_UID|awk '{print tolower($2)}'`
echo $DATE "Diskname: " $DISKNAME  >>$LOG
# Remove hostmap
HOSTMAP=`$SSH svctask rmvdiskhostmap -host $HOSTNAME ganeti_${VOL_NAME}`
echo $DATE "Hostmap: " $HOSTMAP  >>$LOG
# Rescan scsi bus
for i in `seq 1 2`; do echo "- - -" > /sys/class/scsi_host/host$i/scan; done
echo $DATE "Rescan SCSI bus"  >>$LOG
#/etc/init.d/multipath-tools restart
# rescan devmaps
DEVMAPS=`multipath -r`
echo $DATE "Devmaps: " $DEVMAPS  >>$LOG
# Flush multipath
FLUSH=`multipath -f $DISKNAME`
echo $DATE "Flush: " $FLUSH  >>$LOG
